# Generated by Django 3.2.8 on 2023-01-09 07:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_rank_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('type_name', models.CharField(max_length=512, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
        migrations.CreateModel(
            name='ErrorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('traceback_info', models.TextField(help_text='Stack of functions calls.', verbose_name='traceback')),
                ('filename', models.CharField(blank=True, help_text='File where error raised.', max_length=256, null=True)),
                ('line', models.IntegerField(blank=True, help_text='Line number where error raised.', null=True)),
                ('details', models.TextField(blank=True, help_text='Details that may help understand error.', null=True)),
                ('data', models.TextField(blank=True, help_text='Data that used.', null=True)),
                ('campaign', models.ForeignKey(help_text='In which campaign exception is occur.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campaign')),
                ('group', models.ForeignKey(help_text='Group of the exception', on_delete=django.db.models.deletion.CASCADE, to='api.errorgroup')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CampaignInterface),
        ),
    ]
